function servers = getServersList
    %% Outputs the current list of data servers, by priority order.
    
    servers = { ...
    '\\zenneth.cortexlab.net\Subjects\'; ... 
    '\\zortex.cortexlab.net\Subjects\'; ... 
    '\\zaru.cortexlab.net\Subjects\'; ... 
    '\\zinu.cortexlab.net\Subjects\'; ...   
    '\\znas.cortexlab.net\Subjects\'; ... 
    };