clear params
params.subject  = {['AV036']};
params.expDate = {['all']}; 

%params.expNum = '3'; 
params.expDef = 'm'; 
params.checkEvents = '1'; 
%params.expNum = '1'; 
params.expDate = {['2023-04-04:2023-04-28']}; 
exp2checkList = csv.queryExp(params);

%%
figure; 

controlfit = plts.behaviour.glmFit(exp2checkList,...
    'modelString','simpLogSplitVSplitA',...
    'useLaserTrials',0, ...
    'plotType','res',...
     'fitLineStyle','-',...
    'useCurrentAxes',1,...
     'datDotStyle','*');


plts.behaviour.glmFit(exp2checkList,...
    'modelString','simpLogSplitVSplitA',...
    'useLaserTrials',1, ...
    'plotType','res',...
     'fitLineStyle','None',...
    'useCurrentAxes',1,...
     'datDotStyle','o',...
     'laserTrialType',1);

%% day-by-day plot 
nExps = size(exp2checkList); nExps = nExps(1); 
for i=1:nExps
    figure; 
    
    currexp = exp2checkList(i,:);
    controlfit = plts.behaviour.glmFit(currexp,...
        'modelString','simpLogSplitVSplitA',...
        'useLaserTrials',0, ...
        'plotType','res',...
         'fitLineStyle','-',...
        'useCurrentAxes',1,...
         'datDotStyle','*');
    
    
    plts.behaviour.glmFit(currexp,...
        'modelString','simpLogSplitVSplitA',...
        'useLaserTrials',1, ...
        'plotType','res',...
         'fitLineStyle','None',...
        'useCurrentAxes',1,...
         'datDotStyle','o',...
         'laserTrialType',nan);

end 
