function [eventTimes, trialGroups, opt] = conflict(ev)

    opt = struct;
    choiceLabels = (ev.response_direction*2-3).*(ev.response_direction>0);
    choiceNames = {'MoveL'; 'Timeout'; 'MoveR'}; 


    eventTimes = {...
        ev.timeline_visPeriodOnOff(ev.is_conflictTrial,1); ...
        ev.timeline_audPeriodOnOff(ev.is_conflictTrial,1); ...
        ev.timeline_choiceMoveOn(ev.is_conflictTrial); ...
        };

    opt.eventNames = {...
        'Vis Onset'; ...
        'Aud Onset'; ...
        'Movement Onset'; ...
        };

    trialGroups = {...
        [sign(ev.stim_visAzimuth(ev.is_conflictTrial)), choiceLabels(ev.is_conflictTrial)]; ...
        [sign(ev.stim_audAzimuth(ev.is_conflictTrial)), choiceLabels(ev.is_conflictTrial)]; ...
        [choiceLabels(ev.is_conflictTrial)]; ...
        };

    opt.groupNames = {...
        {'Vis Azimuth', 'Choice'} ...
        {'Aud Azimuth', 'Choice'} ...
        {'Choice'} ...
        };


    %         opt.groupNames = {...
%             {{'visL'; 'visR'}, choiceNames, trialNames} ...
%             {{'audL'; 'aud0'; 'audR'}, choiceNames, trialNames} ...
%             {choiceNames, trialNames} ...
%             };


    opt.sortClusters = 'sig';
    opt.sortTrials = repmat({ev.timeline_choiceMoveOn(ev.is_conflictTrial)}, length(eventTimes),1);
    opt.trialTickTimes = repmat({ev.timeline_choiceMoveOn(ev.is_conflictTrial)}, length(eventTimes),1);
end


