 function data4Gui = defaultActivePassive(dataTbl)
%%
if height(dataTbl) == 2 && contains(preproc.getExpDefRef(dataTbl.expDef{1}), 'Passive')
    dataTbl = dataTbl([2 1],:);
end
data4Gui = struct;
for i = 1:height(dataTbl)
    ev = dataTbl.dataEvents{i};    
    if contains(preproc.getExpDefRef(dataTbl.expDef{i}), 'Training')
        data4Gui.subject{i,1} = dataTbl.subject{i};
        data4Gui.expDate{i,1} = dataTbl.expDate{i};
        data4Gui.plotName{i,1} = 'Active';
        data4Gui.spks{i,1} = dataTbl.dataSpikes{i};
        
        choiceNames = {'MoveL'; 'Timeout'; 'MoveR'};
        choiceLabels = (ev.response_direction*2-3).*(ev.response_direction>0);

        trialLabels = ...
            +1*ev.is_blankTrial ...
            +2*ev.is_auditoryTrial...
            +3*ev.is_visualTrial...
            +4*ev.is_coherentTrial ...
            +5*ev.is_conflictTrial;
        trialNames = {'Blank'; 'Aud'; 'Vis'; 'Coherent'; 'Conflict'};

        data4Gui.evTimes{i,1} = {...
            ev.timeline_visPeriodOn; ...
            ev.timeline_audPeriodOn; ...
            ev.timeline_choiceMoveOn; ...
            };

        data4Gui.evNames{i,1} = {...
            'Vis Onset'; ...
            'Aud Onset'; ...
            'Move Onset'; ...
            };

        data4Gui.triGrps{i,1} = {...
            [sign(ev.stim_visAzimuth), choiceLabels]; ...
            [sign(ev.stim_audAzimuth), choiceLabels]; ...
            [choiceLabels]; ...
            };

        data4Gui.grpNames{i,1} = {...
            {'Vis Azimuth', 'Choice'}; ...
            {'Aud Azimuth', 'Choice'}; ...
            {'Choice'}; ...
            };

        data4Gui.sortTemplates{i,1} = 'sig';
        data4Gui.sortTrials{i,1} = repmat({ev.timeline_choiceMoveOn}, length(data4Gui.evTimes{i,1}),1);
        data4Gui.trialTickTimes{i,1} = repmat({ev.timeline_choiceMoveOn}, length(data4Gui.evTimes{i,1}),1);

    elseif contains(preproc.getExpDefRef(dataTbl.expDef{i}), 'Passive')
        data4Gui.subject{i,1} = dataTbl.subject{i};
        data4Gui.expDate{i,1} = dataTbl.expDate{i};
        data4Gui.plotName{i,1} = 'Passive';
        data4Gui.spks{i,1} = dataTbl.dataSpikes{i};

        data4Gui.evTimes{i,1} = {...
            ev.timeline_visPeriodOn; ...
            ev.timeline_audPeriodOn; ...
            };
        
        data4Gui.evNames{i,1} = {...
            'Vis Onset'; ...
            'Aud Onset'; ...
            };
        
        trialLabels = ...
            +1*ev.is_blankTrial ...
            +2*ev.is_auditoryTrial...
            +3*ev.is_visualTrial...
            +4*ev.is_coherentTrial ...
            +5*ev.is_conflictTrial;
        trialNames = {'Blank'; 'Aud'; 'Vis'; 'Coherent'; 'Conflict'};

        data4Gui.triGrps{i,1} = {...
            [sign(ev.stim_visAzimuth)]; ...
            [sign(ev.stim_audAzimuth)]; ...
            };

        data4Gui.grpNames{i,1} = {...
            {'Vis Azimuth'}; ...
            {'Aud Azimuth'};...
            };

        data4Gui.sortTemplates{i,1} = 'sig';
        data4Gui.sortTrials{i,1} = {};
        data4Gui.trialTickTimes{i,1} = {};
    end
end
